name: Bazel
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux, linuxarm]
    steps:
      - uses: actions/checkout@v3
      - name: Build CockroachDB
        run: bash build.sh $arch
        env:
          arch: ${{ matrix.arch }}
